// Departments participants pick from during onboarding. Shown on the leaderboard.
export const DEPARTMENTS = [
  "Analytics",
  "Banking",
  "Business",
  "Call Center",
  "Concierge",
  "COO Office",
  "Corporate Real Estate & Workplace Services",
  "Curlec",
  "Customer Success",
  "Design",
  "Engineering",
  "Enterprise Sales",
  "Finance",
  "Founder's Office",
  "Group Compliance",
  "GTM",
  "Key Account Management",
  "Learning and Development",
  "Legal",
  "MagicCheckout",
  "Marketing",
  "Mid Market",
  "New Initiatives Team",
  "Online Payments Sales",
  "Partnerships",
  "People Operations",
  "Product",
  "Risk",
  "Sales",
  "SME",
  "Solutions",
  "Strategy",
  "Underwriting & Risk",
  "Vigilance",
] as const;

export type Department = (typeof DEPARTMENTS)[number];
